# Generated by Django 3.2.7 on 2021-10-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_privatechatroomrecordmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroomrecordmanager',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
